version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached
      - $HOME/.ssh/:/home/vscode/.ssh/

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    extra_hosts:
      - "host.docker.internal:host-gateway"

  selenium:
    image: seleniarm/standalone-chromium
    restart: unless-stopped

  db:
    image: postgres:16
    restart: unless-stopped
    command: postgres -c "pg_stat_statements.track=all" -c "shared_preload_libraries=pg_stat_statements"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      # Your config/database.yml should use the user and password you set here,
      # and host "db" (as that's the name of this service). You can use whatever
      # database name you want. Use `bin/rails db:prepare` to create the database.
      #
      # Example:
      #
      #  development:
      #    <<: *default
      #    host: db
      #    username: postgres
      #    password: postgres
      #    database: myapp_development

      # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
      # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    image: redis:7.2.5
    restart: unless-stopped
    volumes:
      - redis-data:/data
    ports:
      - 6379:6379

  memcached:
    image: memcached:1.6.28
    restart: unless-stopped
    volumes:
      - memcached-data:/var/lib/memcached/data
    ports:
      - 11211:11211

  meilisearch:
    image: getmeili/meilisearch:v1.8.3
    restart: unless-stopped
    volumes:
      - meilisearch-data:/meili_data
    ports:
      - 7700:7700

volumes:
  postgres-data:
  redis-data:
  memcached-data:
  meilisearch-data:
